# Generated by Django 2.1.5 on 2019-02-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='sections',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.Sections'),
            preserve_default=False,
        ),
    ]
